### ISSUE TITLE
Source files added to all targets, duplicate references

### ISSUE THREAD

**Issue by jshier** [devxoul/CocoaSeeds#14]
Seedfile:

``` ruby
github "Alamofire/Alamofire", "swift-2.0", :files => "Source/*.swift"
github "thoughtbot/Argo", "td-swift-2", :files => "Argo/*/*.swift"
github "thoughtbot/Runes", "swift-2.0", :files => "Source/*.swift"
```

I'm attempting to integrate the Swift 2 versions of several libraries and a few issues have cropped up. First and foremost, it seems like at least some of the source files are included more than once, so I get this error:
`error: filename "Operators.swift" used twice: '/Users/jshier/Desktop/project/Seeds/Runes/Source/Operators.swift' and '/Users/jshier/Desktop/project/Seeds/Runes/Source/Operators.swift'`

Second, it looks like all of the source files are included in all of my targets. Is there any way to have them included in only my actual app target?

Also, is that the proper syntax for targeting a branch instead of a tag? It seems to work but I wasn't sure.

**Comment by devxoul** [comment]
1.
There are same file named 'Operators.swift' in 'Runes' and 'Argo':
- https://github.com/thoughtbot/Runes/blob/master/Source/Operators.swift
- https://github.com/thoughtbot/Argo/blob/master/Argo/Operators/Operators.swift

CocoaSeeds includes source files directly, which can occur compiler error when there are multiple files with same name.

Hmm. I think it can be solved by appending repository name as a filename prefix when including files. I'll take a look :)

2.
Of course you can:

``` ruby
target :MyAppTest do
  github "Quick/Quick", "v0.3.1", :files => "Quick/**.{swift,h}"
  github "Quick/Nimble", "v0.4.2", :files => "Nimble/**.{swift,h}"
end
```

3.
No, there isn't. You can use branch instead of tag (and it works), but it's not recommended way. CocoaSeeds doesn't ensure that the files are up to date.

**Comment by devxoul** [comment]
@jshier,
I just made a new feature. Could you please check this PR(#15)?

Thanks! :)

**Comment by jshier** [comment]
@devxoul Thanks for the change, I'll take a look. However, the error reported by Xcode doesn't show the Argo and Runes files conflicting, it shows the Runes file conflicting with itself, which is certainly not something I saw when the files were integrated manually. And I did try renaming one of the files, but I still got the same error no matter what it was named. I'll try the PR branch and report back.

**Comment by devxoul** [comment]
You're right. CocoaSeeds doesn't import same-named files correctly. But Xcode don't allow the multiple files with same name, so it is necessary to make their names different.

You can try this feature by:
1. Remove existing CocoaSeeds `gem uninstall cocoaseeds`
2. Checkout the `filename-prefix` branch.
3. Run `make install`.
4. Remove all `import Runes` and `import Box` from Argo source files. (I think CocoaSeeds should do this automatically...)

**Comment by jshier** [comment]
I've tried the branch and it works as expected. That, coupled with the target syntax you showed, has gotten me most of the way to the solution I need. Official branch support would be nice, as well as pre and post script support (or perhaps it already exists and just needs documentation?). I've opened #16 for hook support.

**Comment by devxoul** [comment]
Great!
Pre and post scripts are not implemented yet. I've also made #17 for following-up branch support.

Thank you for your time, @jshier :smile::+1:

**Comment by bayarmanlai** [comment]
@devxoul Thanks for awesome tool,
swift_seedname_prefix!  solves duplicated file names, but there is still has problem.
Which is class names duplicate error. Do you have any idea to solve it.

Thanks in advance

**Comment by devxoul** [comment]
@bayarmanlai, sadly CocoaSeeds cannot resolve the class name duplications :( If those classes are exactly the same, you can consider [excluding](https://github.com/devxoul/CocoaSeeds#excluding-files) one.
