### ISSUE TITLE
What happens to (Swift) module namespaces?

### ISSUE THREAD

**Issue by mhuusko5** [devxoul/CocoaSeeds#26]
Doesn't just throwing the Swift files into the project flatten namespaces? This would break a lot of libraries..

**Comment by devxoul** [comment]
@mhuusko5, Sorry I couldn't understand what you exactly talking about.
If you're looking for the way to resolve file name conflicts, see [Resolving Filename Conflicts](https://github.com/devxoul/CocoaSeeds#resolving-filename-conflicts) in README.

**Comment by mhuusko5** [comment]
Swift frameworks are modules, which have namespaces.
For example, Alamofire has the class 'Manager'. The class is 'Alamofire.Manager' when the framework gets built.
If you just drag in the file from Alamofire that contains the class 'Manager' and integrate it into your project, the class just becomes 'Manager'.
If your app, or any other libraries being included via CocoaSeeds includes a class named 'Manager,' there will be a conflict.

You're also going to have build issues if any libraries reference their or other namespaces explicitly, since they won't exist.

**Comment by devxoul** [comment]
Oh, I got it.

Sadly, there is no way to keep their namespaces because CocoaSeeds uses source files directly rather than dynamic frameworks.

I tried to encapsulate all the source files with `struct` with its own framework name, but it cannot solve the `import` issue. (Also have an idea to remove all the `import` statements just after source files are downloaded...)

If you have any idea to solve the problem, please let me know.

**Comment by hfossli** [comment]
Sounds like a dealbreaker... :(

**Comment by hfossli** [comment]
@mhuusko5 so how does this work with the objective-c briding headers? I mean, won't the same issue rise there? A swift nsobject class called "Manager" in Alamofire will have the name "Manager" in Objective-C, won't it?

**Comment by hfossli** [comment]
```
NSLog(@"%@", [TestStuff class]);
```

yields

```
2015-11-09 12:13:07.321 ALERTClient[95628:1669287] ALERT.TestStuff
```

**Comment by hfossli** [comment]
So it seems like the classes are prefixed with modulename....

**Comment by mhuusko5** [comment]
@hfossli to expose a Swift class to Objective-C you have to make it with `@objc`
Optionally you can mark it with `@objc(some-alternate-or-prefixed-class-name)` to expose it with a non clashing name, since there is no namespacing

I think this issue can be closed now though. The basis of all of Swift projects/architecture is modules. Without modules, everything falls apart. I only opened the issue out of curiosity about whether some genius workaround/hack had been devised (struct wrapping doesn't work for most cases)
