### ISSUE TITLE
Specify xcodeproj path

### ISSUE THREAD

**Issue by tbaranes** [devxoul/CocoaSeeds#27]
Is it possible to set a specific path for the xcodeproj?
That could be useful when the xcodeproj isn't in the main directory of the project (by using workspace...)

**Comment by devxoul** [comment]
@tbaranes, Currently it's not possible with CocoaSeeds, but I think it can be easily implemented.

Something like this:

``` bash
$ seed install --project path/to/Project.xcodeproj
```

Does it look good?

**Comment by tbaranes** [comment]
I think, the easiest / best way should be to specify it directly in the Seedfile, but your solution will do the job until a better implementation.

Thanks ! :)

**Comment by devxoul** [comment]
Seedfile looks more great.

<pre>
<b>project "/path/to/Project.xcodeproj"</b>
target :MyApp do
  # ...
end
</pre>

**Comment by tbaranes** [comment]
Since CocoaSeeds supports only the xcodeproj, it could even be: `xcodeproj "/path/to/Project.xcodeproj"`
It's more readable, isn't it?

**Comment by tbaranes** [comment]
Hey! Any updates about that features? I really miss it... :(

**Comment by devxoul** [comment]
@tbaranes, sorry for delay. #46 is what you need!

You can test this feature by cloning CocoaSeeds and running Makefile.

``` bash
$ git clone https://github.com/devxoul/CocoaSeeds -b xcodeproj-path
$ cd CocoaSeeds
$ make
```

If it works, I'll merge it to master and make a new release.

**Comment by tbaranes** [comment]
Works perfectly, thanks :+1: 
I let you close this issue once it's released.
