### ISSUE TITLE
Make 'tag' optional, or allow 'HEAD' or specific revision

### ISSUE THREAD

**Issue by iljaiwas** [devxoul/CocoaSeeds#28]
There are authors on GitHub who don't like to tag their code releases. That makes it quite cumbersome to use their code from CocoaSeeds.

Can we get a little more flexible with the "tag" required, e.g. allowing for "HEAD", or a specific commit hash would be awesome.

Thanks for considering.

**Comment by tbaranes** [comment]
+1, a specific commit would be great!

**Comment by devxoul** [comment]
@iljaiwas, It'll be great if CocoaSeeds supports downloading sources from specific commit. Alternatively, CocoaSeeds currently supports [branch](https://github.com/devxoul/CocoaSeeds#branch-support).

I'll soon make it available :)

**Comment by devxoul** [comment]
@iljaiwas @tbaranes, Hi! This is for you guys: #38

**Comment by devxoul** [comment]
This has been shipped in [0.4.0 release](https://github.com/devxoul/CocoaSeeds/releases/tag/0.4.0) :smile:
