### ISSUE TITLE
Add support for "exclude_files" pattern

### ISSUE THREAD

**Issue by iljaiwas** [devxoul/CocoaSeeds#29]
There are complex projects out there, like Typhoon. In order to easily use this projects with CocoaSeeds, it would be helpful to have an "exclude_files" pattern, that removes specific files from the project that have been previously matched by the "files" pattern.

For instance, if you take a look at the Typhoon pod spec (https://github.com/CocoaPods/Specs/blob/master/Specs/Typhoon/3.3.3/Typhoon.podspec.json), you'll see that when building for iOS, they exclude the OS X directory and vice versa. I guess that's rather hard to do in Typhoon at the moment.

**Comment by devxoul** [comment]
Great idea @iljaiwas! It can be done easily.

**Comment by devxoul** [comment]
Hi @iljaiwas, sorry for delay. PR #41 makes it available what you need.

If it works properly, I'll ship this PR in 0.5.0 release.

PS: I'm also not a ruby programmer, this it my first ruby project in my life :satisfied:

**Comment by iljaiwas** [comment]
Thank you. Will give it a try shortly.
