### ISSUE TITLE
error when I try to install.

### ISSUE THREAD

**Issue by mishagray** [devxoul/CocoaSeeds#42]
I'm using Xcode 7.1, but I get this:
Xcode 7.1 bug?

Anaylizing dependencies
Installing ReactiveCocoa swift2 (was )
Configuring CoverPages.xcodeproj
/Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:510:in `block in configure_phase': undefined method`sources_build_phase' for #Xcodeproj::Project::Object::PBXAggregateTarget:0x007f93bb8498f0 (NoMethodError)
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:509:in `each'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:509:in`configure_phase'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/core.rb:108:in `install'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/lib/cocoaseeds/command.rb:11:in`run'
    from /Users/mgray/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoaseeds-0.5.0/bin/seed:5:in `<top (required)>'
    from /Users/mgray/.rbenv/versions/2.2.0/bin/seed:23:in`load'
    from /Users/mgray/.rbenv/versions/2.2.0/bin/seed:23:in `<main>'

My Seedfile:
target :CoverPages do
  github "ReactiveCocoa/ReactiveCocoa", "swift2", :files => "ReactiveCocoa/Swift/**.{swift,h,m}"
end

**Comment by devxoul** [comment]
This is CocoaSeeds bug. I'll fix it now. Thank you for your report!

**Comment by devxoul** [comment]
Bug fixed version has shipped with [0.5.1 release](https://github.com/devxoul/CocoaSeeds/releases/tag/0.5.1) :)
