### ISSUE TITLE
xcodeproj dependency is too old to update cocoapods

### ISSUE THREAD

**Issue by argon** [devxoul/CocoaSeeds#45]
We use CocoaPods alongside CocoaSeeds but it is not possible for us to update to CocoaPods@0.39.1 because the `xcodeproj` version dependency conflicts.

Could you please update CocoaSeeds to depend on the latest version?

**Comment by devxoul** [comment]
No problem!

**Comment by devxoul** [comment]
2c11c88050e22029beddd18eff72603f46c95879 resolves this issue and this commit has been shipped in [0.5.3 release](https://github.com/devxoul/CocoaSeeds/releases/tag/0.5.3).
