### ISSUE TITLE
When using :commit, :exclude_files will be ignored.

### ISSUE THREAD

**Issue by kennytm** [devxoul/CocoaSeeds#51]
Seedfile:

``` ruby
github 'PavelKatunin/DownloadButton', :commit=>'ff7e3f7', :files=>'Pod/Classes/*.{h,m}', :exclude_files=>'Pod/Classes/*.{h,m}'
```

I expect Cocoa Seeds import nothing into the XCode project. Instead, the `:exclude_files` is silently ignored.

**Comment by kennytm** [comment]
The problem is in core.rb:

``` ruby
          elsif tag.is_a?(Hash)
            seed.commit = tag[:commit][0..6]
            seed.files = tag[:files] || '**/*.{h,m,mm,swift}'
            seed.exclude_files = options[:exclude_files] || []  # ← should be `tag`
          end
```

I'll make a PR when I've got time to write the test case.

**Comment by devxoul** [comment]
@kennytm, Thank you for reporting!
I've made a new PR which fixes this bug: #52

Could you please try with that?
Thanks!

**Comment by kennytm** [comment]
@devxoul Hi sorry for long delay. Yes #52 does fix this. Thanks!

**Comment by devxoul** [comment]
Thanks. I'll merge it and make a new release.
