### ISSUE TITLE
Do you support remove unused files in seed folder?

### ISSUE THREAD

**Issue by kimsungwhee** [devxoul/CocoaSeeds#57]
[Seed/xxxx/_._] folder found there are many unused files below, and the presence .git folder inside the file, causing Git project can not add [Seed/xxxx/_._] track.
I just want to keep [: files => ". Source / \* {swift, h}"] referenced files saved at the Seed folder.

<img width="404" alt="001" src="https://cloud.githubusercontent.com/assets/646158/12999858/0f4b2d00-d197-11e5-8a3f-c65e00a1753c.png">

<img width="410" alt="002" src="https://cloud.githubusercontent.com/assets/646158/12999862/14fdac28-d197-11e5-8142-9569fcfae201.png">

**Comment by devxoul** [comment]
@kimsungwhee, I recommend you to add **`Seeds`** folder under **`.gitignore`**. There's no reason to keep Seeds folder in version control system.

**Comment by kimsungwhee** [comment]
@devxoul ,I see,but in my case jenkins sever not support cocoaseeds. So i want keep seeds folder in version control system.
I found the following code exists in the file which core.rb.
`unusing_files = seedgroup.files - self.file_references
        unusing_files.each { |file| file.remove_from_project }`
Can you give me some idea to remove unusing files?
thanks.

**Comment by devxoul** [comment]
@kimsungwhee, it's not supported now. However, you can make a ruby script to make it available. Put this code in your **`Seedfile`**.

``` ruby
target :MyApp do
    github .....
end

class Seeds::Core
  original_install_seeds = instance_method(:install_seeds)

  define_method(:install_seeds) do
    original_install_seeds.bind(self).()
    post_install
  end

  def post_install
    # here to remove unnecessary files
    `rm -rf Seeds/Alamofire/.git`
  end
end
```

**Comment by kimsungwhee** [comment]
@devxoul ,Thank you very much.
