### ISSUE TITLE
comparison of array with array failed ...

### ISSUE THREAD

**Issue by germanger** [devxoul/CocoaSeeds#6]
This is my Seedfile:

```
     github "Alamofire/Alamofire", "1.2.1", :files => "Source/*.{swift,h}"
     github "devxoul/JLToast", "1.2.2", :files => "JLToast/*.{swift,h}"
     github "SwiftyJSON", "2.2", :files => "Source/SwiftyJSON.swift"
```

I run "seed install", and I get this:

Anaylizing dependencies
/Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/core.rb:239:in `sort': comparison of Array with Array failed (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/core.rb:239:in`install_seeds'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/core.rb:100:in `install'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/command.rb:7:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/bin/seed:5:in `<top (required)>'
    from /usr/bin/seed:23:in`load'
    from /usr/bin/seed:23:in `<main>'

**Comment by devxoul** [comment]
Hi, @germanger!

You should:
1) specify github username for SwiftyJSON.
2) use specific version name (`2.2.0`) instead of `2.2`.

**Before**

``` ruby
github "SwiftyJSON", "2.2", :files => "Source/SwiftyJSON.swift"
```

**After**

``` ruby
github "SwiftyJSON/SwiftyJSON", "2.2.0", :files => "Source/SwiftyJSON.swift"
```

Thanks for using CocoaSeeds :smile:

**Comment by germanger** [comment]
Thanks devxsoul for the fast response.

I made both changes but got this:

```
       seed install
        Anaylizing dependencies
        /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/core.rb:218:in `eval': (eval):3: syntax error, unexpected tCONSTANT, expecting end-of-input (SyntaxError)
        ... “2.2.0”, :files => "Source/SwiftyJSON.swift"
        ...                               ^
        from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/core.rb:218:in `execute_seedfile'
from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/core.rb:98:in `install'
from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/lib/cocoaseeds/command.rb:7:in `run'
from /Library/Ruby/Gems/2.0.0/gems/cocoaseeds-0.0.7/bin/seed:5:in `<top (required)>'
from /usr/bin/seed:23:in `load'
from /usr/bin/seed:23:in `<main>'
```

**Comment by devxoul** [comment]
@germanger,

You're using smart-quotes(“”). Try using regular quotes("").

> ```
> ... “2.2.0”, :files => "Source/SwiftyJSON.swift"
> ... ^
> ```

**Comment by germanger** [comment]
ohhh.. damn, you are right.
Thank you again

**Comment by devxoul** [comment]
If you have any questions or any ideas, please don't hesitate to make an issue :)
