### ISSUE TITLE
Storyboard building tests when using IBDesignable

### ISSUE THREAD

**Issue by acecilia** [devxoul/CocoaSeeds#60]
Hi devxoul:
I am using cocoaseeds in one of my projects. When added [Cosmos](https://github.com/marketplacer/Cosmos) to my project and use it in a storyboard, interface builder builds my main target but also the unit and UI tests targets. Without using Cosmos it only builds the main target (what I think is the right thing). I leave you here the steps to reproduce the problem. 

First I added this line to my seedsfile:
`github "marketplacer/Cosmos", "ios-7-support", :files => "Cosmos/**/*.swift"`

Then I updated the seeds with seed install (similar to pod install).  
After that I created a view in my storyboard and added the CosmosView class.  
Then I clicked on Editor->Refresh all views.  

The result was that interface builder was building the project and also the unit and UI tests. Without using the CosmosView in the storyboard it is just building the project target, not the tests targets (the right thing, why do we need tests at this point??). To avoid building the tests I removed the cosmos files from the "Compile sources" section in my test targets (inside project -> Build Phases). I think they where added there automatically when seed install. 

there is a small discussion about this [here](https://github.com/marketplacer/Cosmos/pull/28). I am not sure if it is an issue or a bad configuration of my project.

Thanks!

**Comment by devxoul** [comment]
Hi @acecilia! You can specify the target in Seedfile.

For example:

``` ruby
target :MyTarget do
  github "marketplacer/Cosmos", "ios-7-support", :files => "Cosmos/**/*.swift"
end
```

This will not add source files to test target. You can find a full documentation [here](https://github.com/devxoul/CocoaSeeds#specifying-targets) :smile:

**Comment by acecilia** [comment]
Oooookey thanks a lot! :)
