### ISSUE TITLE
help needed to add promisekit!

### ISSUE THREAD

**Issue by bayarmanlai** [devxoul/CocoaSeeds#62]
After adding promisekit, xcode build gives me unresolved identifier errors.

<img width="374" alt="screen shot 2016-09-08 at 1 19 28 pm" src="https://cloud.githubusercontent.com/assets/2254704/18336935/e63e4b48-75c6-11e6-9540-9c38c8172f96.png">

What should I do?

Thanks in advance

**Comment by devxoul** [comment]
@bayarmanlai, could you please attach your `Seedfile`?

**Comment by bayarmanlai** [comment]
@devxoul  line for PromiseKit is
github "mxcl/PromiseKit", "3.5.1", :files => "Sources/*.{h,m,swift}"

**Comment by devxoul** [comment]
@bayarmanlai, this is caused by `#import <PromiseKit/...>`. With this, you have to 1) create an objective-c bridging header and 2) replace `#import <>` with `#import ""`.

**Bridging-Header.h**

``` objc
#import "PromiseKit.h"
```

**Seedfile**

``` ruby
github "mxcl/PromiseKit", "3.5.1",
  :files => "Sources/*.{h,m,swift}",
  :exclude_files => [
    "Sources/PMKCallVariadicBlock.m",
  ]

class Seeds::Core
  original_install_seeds = instance_method(:install_seeds)

  define_method(:install_seeds) do
    original_install_seeds.bind(self).()
    post_install
  end

  def post_install
    pattern = '#import <PromiseKit\/\(.*\)>'
    replace = '#import "\1"'


    arr = `grep "#import <PromiseKit" Seeds/PromiseKit/Sources/*.{h,m,swift}`
    filenames = Set.new arr.lines.map { |line| line.split(':')[0] }
    for filename in filenames do
      `sed 's/#{pattern}/#{replace}/g' #{filename} > #{filename}_`
      `rm #{filename} && mv #{filename}_ #{filename}`
    end
  end
end
```
