### ISSUE TITLE
Question: How to use Alamofire after installing with CocoaSeeds?

### ISSUE THREAD

**Issue by germanger** [devxoul/CocoaSeeds#8]
Sorry to start a new thread, but the other one was an issue, and this one is only a question.

I've succesfully installed Alamofire, JLToast and SwiftyJson. All three with CocoaSeeds (`seed install`)

I open mi project and go check the usage of these three (invokations), and this is what I see:
1. When I'm using `JLToast.makeText(...)`, thats fine, no errors.
2. When I'm using `JSON` (which is a struct from SwiftyJson), eg:
   
   ```
           static func fromJSON(json: JSON) -> Place {
                 var place:Place = Place()
                 place.placeId = json["placeId"].intValue // <-- SwiftyJson method
                ...etc
   ```
   
   Thats fine too. No errors.
3. When I'm using `Alamofire.request(.GET, "http://....", parameters: ....)`, there is this error:
   `Use of unresolved identifier 'Alamofire'`

So... with SwiftyJson is more clear to see that there arent errors because SwiftyJson just declares a type that I'm later using. But how come JLToast isn't throwing any errors too?

The real question, though, is:
How can I use Alamofire? I've read that I should wrap it in a struct to simulate a namespace, but what do you recommend? I ask because in the README you've put Alamofire as a seed example so you must have use it (I guess)

Thanks!
by the way, I really appreciate that this is the only project out there trying to solve the "pods + IOS7" problem.

**Comment by germanger** [comment]
Oooh, hate when this happends (ask something and solve it instantly).

I've changed `Alamofire.request(.GET, ....)` with `request(.GET, ....)`

**Comment by devxoul** [comment]
Yeah, CocoaSeeds doesn't use dynamic framework. There's no namespace for third party frameworks.
